cn:
  xvkang: 
    redisNameSpace: chepai
    maxRegStudent: 500
    smsCodeRequireValidateUrls: /app/signupAndRegisterUser
    nongyeStartRegCode: 2019001            
    nongyeEndRegCode: 2019150      
    feiNongyeStartRegCode: 1019001         
    feiNongyeEndRegCode: 1019150
    birthdayEnd: 20130831
    birthdayStart: 20120901
    imageCodeRequireValidateUrls: /loginProcessingUrl
# /getValidateCode/sms
    name: zhangsan
#  短信验证码接口
    sms: 
      smsUrl: https://seccf.51welink.com/submitdata/service.asmx/g_Submit
      smsName: dlxinkao
      smsPwd: YsrGj22D
      smsPrdid: 1012808
      smsSign: 【衡中总务处】
      smsMessageFormatString: 您的登录短信验证码%s，该验证码20分钟内有效，请勿泄漏于他人！
      smsMessageAgreeString: 府小提醒您:家长朋友，您的预约号%s，请按时到学校进行资料核查。
      smsMessageNotAgreeString: 府小提醒您:家长朋友，由于您的预约信息有误，预约失败，请重新申请。
      smsMessageReGeneratorRegCodeString: 府小提醒您:家长朋友，您的预约号已重新生成，新的预约号是%s.
      onePhoneOneDayMaxSendCount: 15
    appauth:
      appUrlPrefix: /appauth
      appLoginUrlSuffix: /login
      appLogoutUrlSuffix: /logout
      appPhoneLoginUrlSuffix: /phoneLogin
      jwtExpireTime: 604800
      notAuthCanAccessUrls:
        - /appauth/login
        - /appauth/logout
        - /appauth/phoneLogin
        - /appauth/sendSms
    xunluoRenyuan:
      jwtExpireTime: 604800
      
      